### PR TITLE
feat(1554): applied source integrity to all third party scripts

### PR DESCRIPTION
**Pull request by akhilmhdh**
# Resolves

1554

# Explain the feature/fix

1. Applied source integrity to all third party scripts and style sheet
2. Updated and locked all latest scripts of op components

## Does this PR introduce a breaking change

No

## Screenshots

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

### CODE REVIEW

**Review by riginoommen — APPROVED** [review]

**Review by hybridx — APPROVED** [review]

**Comment by hybridx** [comment]
@akhilmhdh can you update the doc spa as well?

**Review by deshmukhmayur — APPROVED** [review]

**Comment by akhilmhdh** [comment]
@hybridx  @riginoommen  has created another ticket for adopting new SSi for documentation SPA. I also see that environment var is not a straight forward implementation

**Comment by akhilmhdh** [comment]
This can be merged and ill create another PR

**Review by ghanlohar — APPROVED** [review]
LGTM

**Pull request merged**
