### PR TITLE
Fix the path of footer images

### LINKED ISSUE #715: Incorrect background image path in Documentation SPA
## Describe the bug
Documentation SPA's background image isn't being rendered due to an incorrect render of the image's relative path. 

Instead of 
```
url(/get-started/img/op_footer_cubes_illustration_ltr.svg),url(/get-started/img/op_footer_cubes_illustration_rtl.svg)
```
the background image's path is being rendered as 
```
url(/img/op_footer_cubes_illustration_ltr.svg),url(/img/op_footer_cubes_illustration_rtl.svg)
```

## Steps to reproduce
1. Visit the [Documentation SPA](https://beta.one.redhat.com/get-started/).
2. Inspect the footer element.

## Expected behavior
The background image's path should be rendered as 
```
url(/img/op_footer_cubes_illustration_ltr.svg),url(/img/op_footer_cubes_illustration_rtl.svg)
```

## Screenshots

Current Output:
image

Expected Output:
image

## Environment

- Operating System(s): All
- Browser: All

## Tell us more about your product/project and timeline to help prioritize this issue

- Medium Priority issue not very critical as it only affects the UI styling.
- In all probability, the changes need to be made here: https://github.com/1-Platform/one-platform/blob/e55c5b6ae97473e2c6657966767650392282b584/packages/documentation-spa/src/css/custom.css#L57

### PR DESCRIPTION
**Pull request by Saul-BT**
# Fixes #715 

### 

# Explain the feature/fix

The paths of were wrong. I add the parent folder `get-started` to the path to solve this issue :).

## Does this PR introduce a breaking change

No

## Screenshots

N/A

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

### CODE REVIEW

**Review by riginoommen — APPROVED** [review]

**Comment by riginoommen** [comment]
@hybridx Can you please test it

**Review by ghanlohar — APPROVED** [review]

**Comment by hybridx** [comment]
@Saul-BT can you update the footer to the latest version https://www.npmjs.com/package/@one-platform/opc-footer

**Review by deshmukhmayur — CHANGES_REQUESTED** [review]
@Saul-BT as @hybridx mentioned, updating the opc-footer should be a better fix. Can you update the PR with that?

**Comment by riginoommen** [comment]
Hi, Any recent update on this issue

**Comment by deshmukhmayur** [comment]
Closing the PR due to inactivity. Feel free to raise another PR is this is still valid.

**Pull request closed without merging**
