### PR TITLE
fix : added spa suffix for searching spas

### PR DESCRIPTION
**Pull request by soumyadip007**
# Closes/Fixes/Resolves

### 

# Explain the feature/fix

## Screenshots

<details>
<summary>I've added a description in the package.json, using that we can specify what is the suffix of our spa folders and and where the spas are located</summary>

</details>

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demoed and the design review approved?

### CODE REVIEW

**Review by deshmukhmayur — COMMENTED** [review]
@soumyadip007 Can you provide some description for what this does and why it's required?

**Comment by soumyadip007** [comment]
> @soumyadip007 Can you provide some description for what this does and why it's required?

@deshmukhmayur, I've added a description in the package.json, using that we can specify what is the suffix of our spa folders and where the spas are located.

**Comment by deshmukhmayur** [comment]
> > @soumyadip007 Can you provide some description for what this does and why it's required?
> 
> @deshmukhmayur, I've added a description in the package.json, using that we can specify what is the suffix of our spa folders and where the spas are located.

Yes, but what's the purpose/use of that?

**Comment by riginoommen** [comment]
> > > @soumyadip007 Can you provide some description for what this does and why it's required?
> > 
> > 
> > @deshmukhmayur, I've added a description in the package.json, using that we can specify what is the suffix of our spa folders and where the spas are located.
> 
> Yes, but what's the purpose/use of that?

AFAIK he is trying to separate the SPAs and microservices under the packages directory

**Pull request closed without merging**
