### PR TITLE
 Covered few scenarios in 'my projects' tab test(ONEPLAT-1648) 

### PR DESCRIPTION
**Pull request by mudit94**
# Closes/Fixes/Resolves

### 

# Explain the feature/fix

To be able to click on FAQ and Documentation Link

To automate search functionality of systems tab

To randomly select an element from template, location,status dropdowns and verify its listing in the table for systems tab and also verifying pagination

To randomly select a sorting order

## Does this PR introduce a breaking change

No

## Screenshots

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

### CODE REVIEW

**Review by hybridx — APPROVED** [review]

**Comment by hybridx** [comment]
@mudit94 I suppose you can add a small gif of the e2e test, wdy think? Would that help?

**Comment by mudit94** [comment]
test_screenshot
@hybridx

**Review by riginoommen — APPROVED** [review]

**Comment by hybridx** [comment]
@mudit94 can you close this PR? Since you already have another PR which removes the DSAL test cases. https://github.com/1-Platform/one-platform/pull/1300

**Comment by mudit94** [comment]
Closed this PR

**Pull request closed without merging**
