### PR TITLE
hotfix: fixed opc-base package.json for publishing

### PR DESCRIPTION
**Pull request by akhilmhdh**
# Resolves

1. FIxed blocking configuration in package.json of opc-base

## Does this PR introduce a breaking change

No

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

### CODE REVIEW

**Review by hybridx — APPROVED** [review]
LGTM

**Comment by akhilmhdh** [comment]
@hybridx  Kindly go review opc-base package.json before approving this PR so that its not blocking publishing, too many PR for a single thing going on 😅

**Comment by akhilmhdh** [comment]
@hybridx  that was fast

**Comment by hybridx** [comment]
@akhilmhdh did you use generator this time?

**Comment by akhilmhdh** [comment]
@hybridx Yes

**Review by gautamkrishnar — APPROVED** [review]

**Review by gisumit — APPROVED** [review]

**Pull request merged**
