### PR TITLE
Fix: Adding check to initialise app after successful login.

### PR DESCRIPTION
**Pull request by ghanlohar**
# Closes/Fixes/Resolves
ONEPLAT-895
### 

# Explain the feature/fix

Fixing the API failing issue in User Groups SPA.

## Does this PR introduce a breaking change

No

## Screenshots

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

### CODE REVIEW

**Review by riginoommen — COMMENTED** [review]
Changes look good but mention the jira number with it

**Comment by ghanlohar** [comment]
> Changes look good but mention the jira number with it

@riginoommen updated the issue no.

**Review by riginoommen — APPROVED** [review]

**Review by deshmukhmayur — APPROVED** [review]

**Comment by deshmukhmayur** [comment]
> This pull request **introduces 1 alert** when merging [a4dbbae](https://github.com/1-Platform/one-platform/commit/a4dbbaea6b05917b09072d1182d7b5c5369073d6) into [062eb1a](https://github.com/1-Platform/one-platform/commit/062eb1a61cd5b630d9addb8bc935b589bf4e65a0) - [view on LGTM.com](https://lgtm.com/projects/g/1-Platform/one-platform/rev/pr-dc1b43d8ebf83422846e8dfb838f4a69fddf4cfb)
> 
> **new alerts:**
> 
> * 1 for Unused variable, import, function or class

@ghanlohar Can you check this and remove the unused variable?

**Comment by ghanlohar** [comment]
> > This pull request **introduces 1 alert** when merging [a4dbbae](https://github.com/1-Platform/one-platform/commit/a4dbbaea6b05917b09072d1182d7b5c5369073d6) into [062eb1a](https://github.com/1-Platform/one-platform/commit/062eb1a61cd5b630d9addb8bc935b589bf4e65a0) - [view on LGTM.com](https://lgtm.com/projects/g/1-Platform/one-platform/rev/pr-dc1b43d8ebf83422846e8dfb838f4a69fddf4cfb)
> > **new alerts:**
> > 
> > * 1 for Unused variable, import, function or class
> 
> @ghanlohar Can you check this and remove the unused variable?

Yes @deshmukhmayur. Taken care of it already in [this](https://github.com/1-Platform/one-platform/pull/802/commits/0d791104ff85ac1d1a665f872eebc0c1709a4f76) commit.

**Pull request merged**
