### PR TITLE
Fix/#866 - Create provision to manage contacts related to SPA in home service

### LINKED ISSUE #866: Create provision to manage contacts related to SPA in home service
## Describe the solution you'd like

- Roles like email to report issues, stakeholder email, qe email and all

 

   - Structure
```
{
contacts:

{ issue:["mail@test.com", "test@comp.com"], qe:["mail@test.com", "test@comp.com"], stakeholders:["mail@test.com", "test@comp.com"] }
}
```

## Describe alternatives you've considered

None

## Additional context

None

### PR DESCRIPTION
**Pull request by hybridx**
### Resolves #866 

# Explain the feature/fix

Added new schema

## Does this PR introduce a breaking change

No

## Screenshots

N/A

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

### CODE REVIEW

**Review by ghanlohar — APPROVED** [review]
Looks good to me.

**Review by deshmukhmayur — APPROVED** [review]
LGTM. Does this require any change in the home-spa? (for the enum change)

**Comment by hybridx** [comment]
> LGTM. Does this require any change in the home-spa? (for the enum change)

@deshmukhmayur Not the SPA but the SSI. It's non-breaking change

**Comment by deshmukhmayur** [comment]
> > LGTM. Does this require any change in the home-spa? (for the enum change)
> 
> @deshmukhmayur Not the SPA but the SSI. It's non-breaking change

Got it. Looks good to merge.

**Pull request merged**
