### PR TITLE
hotfix: search-spa migrated opc-nav to latest

### PR DESCRIPTION
**Pull request by akhilmhdh**
# Closes

# Explain the feature/fix

1. Migrated search spa  opc-nav to latest one

## Does this PR introduce a breaking change

No

## Screenshots

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

### CODE REVIEW

**Review by ghanlohar — APPROVED** [review]
LGTM

**Review by ghanlohar — CHANGES_REQUESTED** [review]
@akhilmhdh Update the `package.json` version as well

**Review by hybridx — APPROVED** [review]
LGTM

**Review by riginoommen — APPROVED** [review]

**Review by deshmukhmayur — APPROVED** [review]
Just bump up the package version.

**Comment by akhilmhdh** [comment]
Updated

**Review by ghanlohar — APPROVED** [review]
LGTM

**Pull request merged**
