### PR TITLE
fix:(#4902) - Fixed the interpolation of timestamp in the search ui

### PR DESCRIPTION
**Pull request by riginoommen**
# Resolves 4902

### 

# Explain the fix
Fixed the timestamp intepolation issue on the search view. and updated the ids for the search filters

## Does this PR introduce a breaking change

No

## Screenshots
N/A

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

### CODE REVIEW

**Review by ghanlohar — APPROVED** [review]
Looks good to me.

**Comment by sayak-sarkar** [comment]
@riginoommen Please follow the team norms for PR names! :-/

**Comment by sayak-sarkar** [comment]
@riginoommen Here's a quick reminder:

GitHub PRs

- Branch names: <feat/fix/doc>-#issueID
    - If no issue is present, create one. DON’T use JIRA IDs
- Please use prefixes for commits: feat(#IssueID): , chore(#IssueID): , fix(#issueID): , docs(#IssueID): , design(<name>): , test(#issueID):
- In case of EPICS 
    - Making smaller PRs
        - According the JIRAs
    - Working tested and which fulfills acceptance criteria

**Comment by riginoommen** [comment]
Moved the changes to [PR#726](https://github.com/1-Platform/one-platform/pull/726)

**Pull request closed without merging**
