### PR TITLE
test(lighthouse):fix for the failing tests of lighthouse

### PR DESCRIPTION
**Pull request by mudit94**
# Closes/Fixes/Resolves

:fix for the failing tests of lighthouse and ideahub

# Explain the feature/fix

:fix for the failing tests of lighthouse and ideahub
## Does this PR introduce a breaking change

no

## Screenshots

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

### CODE REVIEW

**Comment by riginoommen** [comment]
Somehow i think managing the timeouts is not the right way

**Review by deshmukhmayur — CHANGES_REQUESTED** [review]
Can you remove the ideahub tests from this?
It should not be in this this monorepo. Idea Hub has a separate repository.

> This repository should only contain the things related to the core one-platform.

**Comment by hybridx** [comment]
> Can you remove the ideahub tests from this? It should not be in this this monorepo. Idea Hub has a separate repository.
> 
> > This repository should only contain the things related to the core one-platform.

@deshmukhmayur I think @mudit94 will have to pull from multiple repos while running the tests from Jenkins, that maybe the reason it is in this repo. But I do agree that only things that are one-platform core should be in this repo. @mudit94 is there something we can do about this? I mean is there a way to manage it in Jenkins?

**Review by hybridx — APPROVED** [review]

**Comment by hybridx** [comment]
> > Can you remove the ideahub tests from this? It should not be in this this monorepo. Idea Hub has a separate repository.
> > > This repository should only contain the things related to the core one-platform.
> 
> @deshmukhmayur I think @mudit94 will have to pull from multiple repos while running the tests from Jenkins, that maybe the reason it is in this repo. But I do agree that only things that are one-platform core should be in this repo. @mudit94 is there something we can do about this? I mean is there a way to manage it in Jenkins?

@mudit94 
This should help
```
pipeline {
    agent any
    parameters{ 
        string(defaultValue: 'copyright-x', description: 'Please input SPA name', name: 'spaName', trim: true)
        string(defaultValue: '1.0.0', description: 'Please input the correct reference', name: 'ref', trim: true)
    }
    environment {
        SPA_NAME = "${params.spaName.toLowerCase()}"
    }
    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/hybridx/webcomponents'
                sh """
                echo ${params.ref}
                echo ${SPA_NAME}
                ls
                cd packages/${params.spaName.toLowerCase()}
                ls
                """
                git 'https://github.com/gamedoora/gamedoora-ui'
                sh """
                ls
                """
            }
        }
        stage('Test') {
            steps {
                sh """
                ls
                """
            }
        }
    }
}
```

**Comment by mudit94** [comment]
> Can you remove the ideahub tests from this? It should not be in this this monorepo. Idea Hub has a separate repository.
sure @deshmukhmayur . I will remove the ideahub tests from one platform repo and move to idea hub repo.

@hybridx , the jenkins job may require a lot many change (the entire config style needs a change for it to be possbile . That may be a separate task

**Review by ghanlohar — APPROVED** [review]

**Review by riginoommen — APPROVED** [review]

**Comment by mudit94** [comment]
> Can you remove the ideahub tests from this? It should not be in this this monorepo. Idea Hub has a separate repository.
> 
> > This repository should only contain the things related to the core one-platform.

@deshmukhmayur https://github.com/1-Platform/one-platform/pull/1412/commits/db928f17ec3b83dfadd4ea8da963ce2d1ce3353a  has got ideahub removed

**Review by deshmukhmayur — APPROVED** [review]
@riginoommen @ghanlohar please use squash and merge, and remove "ideahub" from the message when merging

**Review by riginoommen — APPROVED** [review]

**Review by ghanlohar — APPROVED** [review]
LGTM

**Review by hybridx — APPROVED** [review]

**Pull request merged**
